FROM python:3.7-bullseye

WORKDIR /opt

RUN apt-get install -y libpq-dev

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD ["python3", "-m", "alembic", "-n", "cocwa", "upgrade", "head"]
